name: Build (Staging)

on:
  push:
    branches:
      - 'release/**'

jobs:
  restore:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore
  
  build:
    needs: restore
    runs-on: ubuntu-latest
    
    steps:
      - name: Build
        run: dotnet build --configuration Release --no-restore
  
  tests:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Test
        run: dotnet test --no-restore --verbosity normal